@echo off
echo Starting Robot Brain locally...
echo Activating virtual environment...
call ..\venv\Scripts\activate

echo Installing/Updating dependencies...
pip install -r requirements.txt

echo Starting Uvicorn server...
uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
pause
